name: CI Build

on:
  push:
    branches: [ develop,main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ develop,main ]
  workflow_dispatch:
permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true  

jobs:
  build-android:
    runs-on: windows-2022
    name: Android Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
          include-prerelease: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Install MAUI Workloads
        run: |
          dotnet workload install android --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore PwnedPass/PwnedPass.csproj

      - name: Build MAUI Android
        run: dotnet build PwnedPass/PwnedPass.csproj -c Release -f net7.0-android --no-restore

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4.2.0
        with:
          name: android-ci-build
          path: PwnedPass/bin/Release/net7.0-android/*Signed.a*
  build-windows:
    runs-on: windows-2022
    name: Windows Build
    steps:

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Setup .NET 7
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3
        with:
          dotnet-version: 7.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore PwnedPass/PwnedPass.csproj

      - name: Build MAUI Windows
        run: dotnet publish PwnedPass/PwnedPass.csproj -c Release -f net7.0-windows10.0.19041.0 --no-restore /p:PublishReadyToRun=false

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6
        with:
          name: mauibeach-windows-ci-build
          path: PwnedPass/bin/Release/net7.0-windows10.0.19041.0/win10-x64/AppPackages/PwnedPass*/PwnedPass*.msix
